export const layout = [
  { i: "JS", x: 4, y: 0, w: 1, h: 1 },
  { i: "React", x: 5, y: 1, w: 1, h: 1 },
  { i: "Redux", x: 6, y: 0, w: 1, h: 1 },
  { i: "HTML", x: 3, y: 0, w: 1, h: 1 },
  { i: "CSS", x: 2, y: 1, w: 1, h: 1 },
  { i: "Typescript", x: 7, y: 0, w: 1, h: 1 },
  { i: "GraphQL", x: 8, y: 2, w: 1, h: 1 },
  { i: "Material", x: 2, y: 2, w: 1, h: 1 },
  { i: "Figma", x: 5, y: 5, w: 1, h: 1 },
  { i: "styled-components", x: 3, y: 3, w: 1, h: 1 },
  { i: "Wordpress", x: 11, y: 0, w: 1, h: 1 },
  { i: "Firebase", x: 7, y: 3, w: 1, h: 1 },
  { i: "Gatsby", x: 6, y: 4, w: 1, h: 1 },
  { i: "Git", x: 4, y: 4, w: 1, h: 1 },
  { i: "Illustrator", x: 11, y: 3, w: 1, h: 1 },
  { i: "rest-api", x: 8, y: 1, w: 1, h: 1 },
  { i: "Contentful", x: 11, y: 1, w: 1, h: 1 },
  { i: "SEO", x: 11, y: 2, w: 1, h: 1 },
];
export const layoutSmall = [
  { i: "JS", x: 2, y: 0, w: 1, h: 1 },
  { i: "React", x: 3, y: 1, w: 1, h: 1 },
  { i: "Redux", x: 4, y: 0, w: 1, h: 1 },
  { i: "HTML", x: 1, y: 0, w: 1, h: 1 },
  { i: "CSS", x: 0, y: 1, w: 1, h: 1 },
  { i: "Typescript", x: 5, y: 0, w: 1, h: 1 },
  { i: "GraphQL", x: 6, y: 2, w: 1, h: 1 },
  { i: "Material", x: 0, y: 2, w: 1, h: 1 },
  { i: "Figma", x: 3, y: 5, w: 1, h: 1 },
  { i: "styled-components", x: 1, y: 3, w: 1, h: 1 },
  { i: "Wordpress", x: 7, y: 4, w: 1, h: 1 },
  { i: "Firebase", x: 5, y: 3, w: 1, h: 1 },
  { i: "Gatsby", x: 4, y: 4, w: 1, h: 1 },
  { i: "Git", x: 2, y: 4, w: 1, h: 1 },
  { i: "Illustrator", x: 7, y: 2, w: 1, h: 1 },
  { i: "rest-api", x: 6, y: 1, w: 1, h: 1 },
  { i: "Contentful", x: 7, y: 5, w: 1, h: 1 },
  { i: "SEO", x: 7, y: 3, w: 1, h: 1 },
];
