import huntingImg from "../assets/images/hunting.PNG";
import kiteShopImg from "../assets/images/kite-shop-image.PNG";
import adminImg from "../assets/images/admin.PNG";
import arqImg from "../assets/images/ARQProjekt.PNG";
import draggableNote from "../assets/images/draggable-note.PNG";

export const initialDraggableList = [
  {
    id: 2,
    status: false,
    zIndex: 1000,
    projectName: "The Hunting Dog",
    bounds: { left: 0, top: 0, right: 985, bottom: 386 },
    boundsMedium: { left: 0, top: 0, right: 785, bottom: 386 },
    boundsSmall: { left: 0, top: 0, right: 535, bottom: 386 },
    defaultPosition: { x: 50, y: 50 },
    defaultPositionSmall: { x: 50, y: 50 },
    minimalizeStatus: false,
    projectImage: huntingImg,
    wordpress: true,
    buttonLive: "https://www.the-hunting-dog.com/",
    buttonGithub: "",
    description:
      "My biggest commercial WordPress website that I've ranked on Google. This project is 3 years old. During the first two years, I was focused on gaining knowledge about SEO and converting it into action.",
    skills: ["Wordpress", "SEO/SEM"],
  },
  {
    id: 3,
    status: false,
    zIndex: 1000,
    projectName: "Kite Shop",
    bounds: { left: 0, top: -400, right: 985, bottom: -14 },
    boundsMedium: { left: 0, top: -400, right: 785, bottom: -14 },
    boundsSmall: { left: 0, top: -400, right: 535, bottom: -14 },
    defaultPosition: { x: 100, y: -295 },
    defaultPositionSmall: { x: 100, y: -295 },
    minimalizeStatus: false,
    projectImage: kiteShopImg,
    wordpress: false,
    buttonLive: "https://kite-shop-react-app.netlify.app/",
    buttonGithub: "https://github.com/JakubKomorowski/kite_shop_react_app",
    description:
      "It's a project of a fictional online kitesurfing shop. Among the others, this application contains the functionality of sorting, filtering, searching, and adding products to the cart. It’s based on Context Api and Contentful Api. It is styled using Styled-Components and Material-UI. Thanks to this project, I immersed myself in React and learned styled-components.",
    skills: [
      "React",
      "React-Router-Dom",
      "Context API",
      "Contentful CMS",
      "Styled-Components",
      "Formik",
      "Yup",
      "Material-UI",
    ],
  },
  {
    id: 4,
    status: false,
    zIndex: 1000,
    projectName: "Draggable Note List",
    bounds: { left: 0, top: -800, right: 985, bottom: -414 },
    boundsMedium: { left: 0, top: -800, right: 785, bottom: -414 },
    boundsSmall: { left: 0, top: -800, right: 535, bottom: -414 },
    defaultPosition: { x: 150, y: -640 },
    defaultPositionSmall: { x: 150, y: -640 },
    minimalizeStatus: false,
    projectImage: draggableNote,
    wordpress: false,
    buttonLive: "https://draggable-note-list.netlify.app/",
    buttonGithub:
      "https://github.com/JakubKomorowski/draggable-note-list_redux-typescript",
    description:
      "It is a simple draggable note list project. User can drag his note between columns that represents stages of the work process. It’s based on React Redux and TypeScript.",
    skills: [
      "React",
      "Redux",
      "TypeScript",
      "Styled-Components",
      "Material-UI",
    ],
  },
  {
    id: 5,
    status: false,
    zIndex: 1000,
    projectName: "Admin Panel",
    bounds: { left: 0, top: -1200, right: 985, bottom: -814 },
    boundsMedium: { left: 0, top: -1200, right: 785, bottom: -814 },
    boundsSmall: { left: 0, top: -1200, right: 535, bottom: -814 },
    defaultPosition: { x: 200, y: -985 },
    defaultPositionSmall: { x: 200, y: -985 },
    minimalizeStatus: false,
    projectImage: adminImg,
    wordpress: false,
    buttonLive: "https://admin-panel-react-app.netlify.app/",
    buttonGithub: "https://github.com/JakubKomorowski/admin_panel",
    description:
      "Fictional admin panel application that enables users to add and track client's orders. Users can set the delivery date, check if the order is paid and also add, edit and remove products from each order. It’s based on React Redux and Firebase. This project helped me to strengthen my Redux and Material-UI skills.",
    adminPanel: true,
    skills: [
      "React",
      "React-Router-Dom",
      "Redux",
      "Firebase",
      "Styled-Components",
      "Material-UI",
    ],
  },
  {
    id: 6,
    status: false,
    zIndex: 1000,
    projectName: "ARQ Projekt",
    bounds: { left: 0, top: -1600, right: 985, bottom: -1214 },
    boundsMedium: { left: 0, top: -1600, right: 785, bottom: -1214 },
    boundsSmall: { left: 0, top: -1600, right: 535, bottom: -1214 },
    defaultPosition: { x: 250, y: -1330 },
    defaultPositionSmall: { x: 250, y: -1330 },
    minimalizeStatus: false,
    projectImage: arqImg,
    wordpress: false,
    buttonLive: "https://arqprojekt.pl/",
    buttonGithub: "https://github.com/JakubKomorowski/arqprojekt-gatsby",
    description:
      "It is a commercial project built for the real-estate company. It's based on Gatsbyjs - an open-source frontend framework based on React. This framework is known for the good performance and SEO.",
    skills: ["Gatsby", "Styled-Components", "DatoCMS", "GraphQL"],
  },
];
